In [15]:
# 30-06-25, Monday;

# PDBC: Python Database Connectivity.

# Steps:
# 1. import the module.
# 2. Create a connection.
# 3. Create cursor onject.
# 4. Execute SQL queries.
# 5. Commit the changes.
# 6. Close the connection.

# Installed: pip install mysql-connector-python

# E.G.: Create a table and insert data.

import mysql.connector as mysql
import os
from dotenv import load_dotenv #for environment variables.

# Load variables from .env file
load_dotenv()

# Access the environment variables
DB_PASSWORD = os.getenv("DB_PASSWORD")

# Connect
conn = mysql.connect(
    host="localhost",
    user="root",
    password=DB_PASSWORD,
    database="PDBC_1"
)

print(conn)

cursor = conn.cursor()

# Print current database name
cursor.execute("SELECT DATABASE()")
current_db = cursor.fetchone()[0]
print("Connected to database:", current_db)

# Create table without
cursor.execute("""
    CREATE TABLE IF NOT EXISTS hypercars (
        id INT PRIMARY KEY,
        name VARCHAR(50),
        brand VARCHAR(50)
    )
""")

# Insert records manually (only if not exists)
insert_data = [
    (1, "Chiron SS 300+", "Bugatti"),
    (2, "Sadairs Spear", "Koenigsegg"),
    (3, "Huayra", "Pagani"),
    (4, "Devel 16", "Devel")
]

for record in insert_data:
    cursor.execute("SELECT COUNT(*) FROM hypercars WHERE id = %s", (record[0],))
    if cursor.fetchone()[0] == 0:
        cursor.execute("INSERT INTO hypercars (id, name, brand) VALUES (%s, %s, %s)", record)

# Fetch records
cursor.execute("SELECT * FROM hypercars")
rows = cursor.fetchall()
print("\nCurrent Hypercars:")
for row in rows:
    print(row)

conn.commit()
conn.close()

<mysql.connector.connection.MySQLConnection object at 0x000001AC821A58B0>
Connected to database: pdbc_1

Current Hypercars:
(1, 'Chiron SS 300+', 'Bugatti')
(2, 'Sadairs Spear', 'Koenigsegg')
(3, 'Huayra', 'Pagani')
(4, 'Devel 16', 'Devel')