In [30]:
# 30-06-25, Monday;

# PDBC: Python Database Connectivity.

# Steps:
# 1. import the module.
# 2. Create a connection.
# 3. Create cursor onject.
# 4. Execute SQL queries.
# 5. Commit the changes.
# 6. Close the connection.

# Installed: pip install mysql-connector-python

# E.G.: Create a table and insert data.

import mysql.connector as mysql
import os
from dotenv import load_dotenv #for environment variables.

# Load variables from .env file
load_dotenv()

# Access the environment variables
DB_PASSWORD = os.getenv("DB_PASSWORD")

# Connect
conn = mysql.connect(
    host="localhost",
    user="root",
    password=DB_PASSWORD,
    database="PDBC_1"
)

print("Connection to database:",conn)


cursor = conn.cursor()

# Print current database name
cursor.execute("SELECT DATABASE()")
current_db = cursor.fetchone()[0]
print("Connected to database:", current_db)

# Create table without
cursor.execute("""
    CREATE TABLE IF NOT EXISTS hypercars (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(50),
        brand VARCHAR(50)
    )
""")

# Insert records manually (only if not exists)
insert_data = [
    ("Chiron SS 300+", "Bugatti"),
    ("Sadairs Spear", "Koenigsegg"),
    ("Huayra", "Pagani"),
    ("Devel 16", "Devel")
]

for name, brand in insert_data:
    cursor.execute("SELECT COUNT(*) FROM hypercars WHERE name = %s AND brand = %s", (name, brand))
    if cursor.fetchone()[0] == 0:
        cursor.execute("INSERT INTO hypercars (name, brand) VALUES (%s, %s)", (name, brand))

while True:
    print("\nCurrent Hypercars:")
    cursor.execute("SELECT * FROM hypercars;")
    currentCars = cursor.fetchall()
    for record in currentCars:
      print(record)

    print("\n--- Add New Hypercar ---")
    # User input data:
    name = input("Enter new Hypercar Medel:")
    brand = input("Enter new Hypercar Brand:")

    cursor.execute("SELECT COUNT(*) FROM hypercars WHERE name = %s AND brand = %s", (name, brand))
    if cursor.fetchone()[0] == 0:
        cursor.execute("INSERT INTO hypercars (name, brand) VALUES (%s, %s)", (name, brand))
        print("Inserted successfully!")
    else:
        print("Hypercar already exists. Skipping insert.")

    # Fetch & show updated table
    cursor.execute("SELECT * FROM hypercars")
    print("\nCurrent Hypercars in DB:")
    for row in cursor.fetchall():
        print(row)

    cont = input("\nDo you want to add more Hypercars? (Y/N): ")
    if cont.lower() != 'y':
        break
conn.commit()
conn.close()

Connection to database: <mysql.connector.connection.MySQLConnection object at 0x000002343E687320>
Connected to database: pdbc_1

Current Hypercars:
(1, 'Chiron SS 300+', 'Bugatti')
(2, 'Sadairs Spear', 'Koenigsegg')
(3, 'Huayra', 'Pagani')
(4, 'Devel 16', 'Devel')
(5, '812 SF', 'Ferrari')

--- Add New Hypercar ---
Inserted successfully!

Current Hypercars in DB:
(1, 'Chiron SS 300+', 'Bugatti')
(2, 'Sadairs Spear', 'Koenigsegg')
(3, 'Huayra', 'Pagani')
(4, 'Devel 16', 'Devel')
(5, '812 SF', 'Ferrari')
(6, '918 Spyder', 'Porsche')

Current Hypercars:
(1, 'Chiron SS 300+', 'Bugatti')
(2, 'Sadairs Spear', 'Koenigsegg')
(3, 'Huayra', 'Pagani')
(4, 'Devel 16', 'Devel')
(5, '812 SF', 'Ferrari')
(6, '918 Spyder', 'Porsche')

--- Add New Hypercar ---
Inserted successfully!

Current Hypercars in DB:
(1, 'Chiron SS 300+', 'Bugatti')
(2, 'Sadairs Spear', 'Koenigsegg')
(3, 'Huayra', 'Pagani')
(4, 'Devel 16', 'Devel')
(5, '812 SF', 'Ferrari')
(6, '918 Spyder', 'Porsche')
(7, 'Nevera', 'Rimac')

In [23]:
import mysql.connector as mysql
import os
from dotenv import load_dotenv

# Load env
load_dotenv()
DB_PASSWORD = os.getenv("DB_PASSWORD")

# Connect
conn = mysql.connect(
    host="localhost",
    user="root",
    password=DB_PASSWORD,
    database="PDBC_1"
)

print("Connection to database:", conn)
cursor = conn.cursor()

# Print current DB name
cursor.execute("SELECT DATABASE()")
print("Connected to database:", cursor.fetchone()[0])

# Create table
cursor.execute("""
    CREATE TABLE IF NOT EXISTS hypercars (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(50),
        brand VARCHAR(50)
    )
""")

# Predefined records (insert only if not already present)
default_data = [
    ("Chiron SS 300+", "Bugatti"),
    ("Sadairs Spear", "Koenigsegg"),
    ("Huayra", "Pagani"),
    ("Devel 16", "Devel")
]

for name, brand in default_data:
    cursor.execute("SELECT COUNT(*) FROM hypercars WHERE name = %s AND brand = %s", (name, brand))
    if cursor.fetchone()[0] == 0:
        cursor.execute("INSERT INTO hypercars (name, brand) VALUES (%s, %s)", (name, brand))

# ‚úÖ User Input Loop
while True:
    print("\n--- Add New Hypercar ---")
    name = input("Enter new Hypercar Model: ")
    brand = input("Enter new Hypercar Brand: ")

    # Insert only if it's not a duplicate
    cursor.execute("SELECT COUNT(*) FROM hypercars WHERE name = %s AND brand = %s", (name, brand))
    if cursor.fetchone()[0] == 0:
        cursor.execute("INSERT INTO hypercars (name, brand) VALUES (%s, %s)", (name, brand))
        print("‚úÖ Inserted successfully!")
    else:
        print("‚ö†Ô∏è  Hypercar already exists. Skipping insert.")

    # Fetch & show updated table
    cursor.execute("SELECT * FROM hypercars")
    print("\nCurrent Hypercars in DB:")
    for row in cursor.fetchall():
        print(row)

    cont = input("\nDo you want to add more Hypercars? (Y/N): ")
    if cont.lower() != 'y':
        break

# Finish
conn.commit()
conn.close()
print("üîö Connection closed.")

Connection to database: <mysql.connector.connection.MySQLConnection object at 0x000002343D406780>
Connected to database: pdbc_1

Current Hypercars:
(1, 'Chiron SS 300+', 'Bugatti')
(2, 'Sadairs Spear', 'Koenigsegg')
(3, 'Huayra', 'Pagani')
(4, 'Devel 16', 'Devel')

Inserted Hypercars:
(1, 'Chiron SS 300+', 'Bugatti')
(2, 'Sadairs Spear', 'Koenigsegg')
(3, 'Huayra', 'Pagani')
(4, 'Devel 16', 'Devel')
(5, '812 SF', 'Ferrari')
(7, '918 Spyder', 'Porsche')
(8, 'R8 Spyder', 'Audi')
(9, '911 GT2 RS', 'Porsche')
üîö Database connection closed.